name: flutterweb
description: An app built using Flutter for web

environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: '>=2.3.0-dev.0.1 <3.0.0'

dependencies:
  flutter_web: any
  flutter_web_ui: any

dev_dependencies:
  build_runner: ^1.4.0
  build_web_compilers: ^2.0.0
  pedantic: ^1.0.0

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui

assets:
          - assets/images/ic_thumb_11.png
          - assets/images/ic_thumb_12.png
          - assets/images/ic_thumb_13.png
          - assets/images/ic_thumb_21.png
          - assets/images/ic_thumb_31.png
          - assets/images/ic_thumb_41.png
          - assets/images/movie_banner_1.png
          - assets/images/movie_banner_2.png
          - assets/images/movie_banner_3.png
          - assets/images/movie_banner_4.png
          - assets/images/logo.png
          - assets/images/powered_by.png
          - assets/images/ic_preview_1.png
          - assets/images/ic_preview_2.png
          - assets/images/ic_preview_3.png
          - assets/images/ic_preview_4.png